## Introducing the broadcasting

Recall that for arrays of the same size, binary operations are performed on an
element-by-element basis:


Broadcasting allows these types of binary operations to be performed on arrays of dif‐
ferent sizes—for example, we can just as easily add a scalar (think of it as a zerodimensional array) to an array:

In [3]:
import numpy as np


In [4]:
a=np.array([0,1,2,3,4,5,6])

In [5]:
print(a+5)

[ 5  6  7  8  9 10 11]


##### rules of broadcasting

• Rule 1: If the two arrays differ in their number of dimensions, the shape of the
one with fewer dimensions is padded with ones on its leading (left) side.

• Rule 2: If the shape of the two arrays does not match in any dimension, the array
with shape equal to 1 in that dimension is stretched to match the other shape.

• Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is
raised.


###### basically broadcasting is use in numpy when the arrays have the differnet size and and get manage by itself . it helps in computation


###### broadcasting use

In [6]:
 X = np.random.random((10, 3))


In [7]:
 Xmean = X.mean(0)
 Xmean

array([0.48999702, 0.47226233, 0.42727233])

we get the mean of array by using the Xmean

In [8]:
 X_centered = X - Xmean

In [9]:
X_centered.mean(0)


array([ 8.8817842e-17, -4.4408921e-17,  0.0000000e+00])

#### Plotting a two-dimensional function

One place that broadcasting is very useful is in displaying images based on twodimensional functions. If we want to define a function z = f(x, y), broadcasting can be
used to compute the function across the grid:

### Sorting arrays

Fortunately, Python contains built-in sorting algorithms that are much more efficient
than either of the simplistic algorithms just shown. We’ll start by looking at the
Python built-ins, and then take a look at the routines included in NumPy and opti‐
mized for NumPy arrays.

fficient and useful for our purposes. By default np.sort uses an ᇭ N log N , quick‐
sort algorithm, though mergesort and heapsort are also available. For most applica‐
tions, the default quicksort is more than sufficient.

In [12]:
x = np.array([1,10,9,3,4,5,2,1,0])

In [13]:
np.sort(x)

array([ 0,  1,  1,  2,  3,  4,  5,  9, 10])

###### A related function is argsort, which instead returns the indices of the sorted
elements:


In [14]:
x1 = np.array([1,3,2,6,4,5])

In [15]:
np.argsort(x1)

array([0, 2, 1, 4, 5, 3], dtype=int64)

###### Sorting along rows or columns

A useful feature of NumPy’s sorting algorithms is the ability to sort along specific
rows or columns of a multidimensional array using the axis argument. For example:

In [18]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [19]:
np.sort(X, axis=0)


array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [20]:
np.sort(X, axis=1)


array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

##### partial sort partitioning

Sometimes we’re not interested in sorting the entire array, but simply want to find the
K smallest values in the array. NumPy provides this in the np.partition function.
np.partition takes an array and a number K; the result is a new array with the small‐
est K values to the left of the partition, and the remaining values to the right, in arbi‐
trary order:

###### just like finding pivot in quicksort

In [21]:
a = np.array([3,6,8,9,2,4])


In [25]:
np.partition(a, 1)

array([2, 3, 8, 9, 6, 4])

In [26]:
np.partition(a, 4)

array([2, 3, 4, 6, 8, 9])

In [27]:
np.partition(a, 3)

array([2, 3, 4, 6, 8, 9])

In [28]:
np.partition(a, 2)

array([2, 3, 4, 9, 6, 8])